import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { CheckCircle2, Circle } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
export function OnboardingChecklist({ steps, title = 'Launch checklist', description = 'Step-by-step guide so you always know what to do next.', }) {
    return (_jsxs(Card, { className: "border bg-card shadow-sm h-full", children: [_jsxs(CardHeader, { className: "pb-4", children: [_jsx(CardTitle, { className: "text-base font-semibold", children: title }), description && _jsx(CardDescription, { className: "text-sm", children: description })] }), _jsx(CardContent, { className: "space-y-4", children: steps.map((step, index) => (_jsxs("div", { className: "rounded-xl border bg-background/70 p-4 space-y-2", children: [_jsxs("div", { className: "flex items-start gap-3", children: [step.done ? (_jsx(CheckCircle2, { className: "h-5 w-5 text-emerald-500 shrink-0 mt-0.5" })) : (_jsx(Circle, { className: "h-5 w-5 text-muted-foreground shrink-0 mt-0.5" })), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between gap-2", children: [_jsx("p", { className: "text-sm font-semibold text-foreground", children: step.title }), _jsxs(Badge, { variant: "outline", className: "text-[10px]", children: ["Step ", index + 1] })] }), _jsx("p", { className: "text-sm text-muted-foreground", children: step.description })] })] }), step.action &&
                            (step.action.type === 'link' ? (_jsx(Button, { variant: "secondary", size: "sm", className: "w-full", asChild: true, children: _jsx(Link, { to: step.action.to, children: step.action.label }) })) : (_jsx(Button, { variant: "secondary", size: "sm", className: "w-full", onClick: step.action.onClick, disabled: step.action.disabled, children: step.action.label })))] }, step.id))) })] }));
}
